name: Create Release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Installer
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 18
          platform: x64
      - name: Setup External Dependencies
        run: |
          .\install_dependencies.ps1
      - name: Build Installer
        run: |
          .\build_as_ci.ps1
      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: build/ci-release/release/ # path to the release assembled by CMake