name: Create Release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Installer
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 18
          platform: x64
      - name: Setup External Dependencies
        run: |
          .\install_dependencies.ps1
      - name: Build Installer
        run: |
          .\build_as_ci.ps1
      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: build/ci-release/release/ # path to the release assembled by CMake
  make-release:
    runs-on: windows-latest
    permissions:
      contents: write
    needs: build
    steps:
      - name: Download Installer Artifact
        uses: actions/download-artifact@v4
        with:
          path: installer
      - name: Zip Installer
        run: |
          Compress-Archive -Path .\installer -DestinationPath installer.zip
      - name: Sparse checkout changelog
        uses: actions/checkout@v4
        with:
          path: changelog
          sparse-checkout: "CHANGELOG.md"
          sparse-checkout-cone-mode: false
      - name: Parse changelog
        id: parse-changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          path: changelog/CHANGELOG.md
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.zip
          name: ${{ steps.parse-changelog.outputs.version }}
          body: ${{ steps.parse-changelog.outputs.changes }}
          tag_name: ${{ steps.parse-changelog.outputs.version }}